#!/bin/bash -l
set -u

export LC_ALL="en_GB.UTF-8"

dir=`pwd`
host=`hostname`

if [ -r config/$host ]; then
    source config/$host
else
    echo "No configuration for host '$host' in config"
fi

echo Starting script at `date`

pushd $REPOSITORY > /dev/null

echo updating in `pwd`

git remote update
if git diff origin/$BRANCH --quiet; then
  echo no changes, bailing out
#  exit
fi

git checkout $BRANCH
git reset --hard origin/$BRANCH

popd > /dev/null

for file in regression_tests/*; do
  builddir=$(mktemp -d "$TMPDIR/build-XXXXXXXX")

  ctest -DCONFIG_FILE="${dir}/${host}/${file}" \
        -DCTEST_BINARY_DIRECTORY="${builddir}" \
        -DMAKEOPTS="${MAKEOPTS}" \
        -DTRACK="${TRACK}" \
        -S "${REPOSITORY}"/tests/run_testsuite.cmake \
        ${MAKEOPTS} \
        --schedule-random

  rm -rf "${builddir}"
done
